#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp32_exosk_screen

EXTRA_COMPONENT_DIRS := $(abspath ../../components)

include $(MDF_PATH)/project.mk
